# Generated by Django 4.1 on 2024-01-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="Item_Photo",
            field=models.ImageField(upload_to="static/Photos/"),
        ),
    ]
