# Generated by Django 4.1 on 2024-01-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0003_rename_id_products_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="HAE_COST_AED",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="HIGHT_MM",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="LENGTH_MM",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="QTY",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="WIDTH_MM",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
