# Generated by Django 4.1 on 2024-01-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Products",
            "0004_alter_products_hae_cost_aed_alter_products_hight_mm_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="INQUIRY_CODE",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
