# Generated by Django 4.1 on 2024-01-24 07:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0005_products_inquiry_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="HIGHT_MM",
            new_name="HEIGHT_MM",
        ),
    ]
